---
title: "browser_compatibility"
author: "frequena"
date: "13/5/2020"
output:
  html_document:
    toc: true
---

## Database versions

<center>

<table style="width:100%">
<tbody>
<tr>
<td width="247">
<p><strong>Database</strong></p>
</td>
<td width="83">
<p><strong>Version/access date</strong></p>
</td>
<td width="273">
<p><strong>Link</strong></p>
</td>
</tr>
<tr>
<td width="247">
<p>Database of Genomic Variants (DGV)</p>
</td>
<td width="83">
<p>2020-02-25</p>
</td>
<td width="273">
<p>&nbsp;http://dgv.tcag.ca/dgv/app/home</p>
</td>
</tr>
<tr>
<td width="247">
<p>DECIPHER CNVs</p>
</td>
<td width="83">
<p>2020-01-19</p>
</td>
<td width="273">
<p>http://decipher.sanger.ac.uk/</p>
</td>
</tr>
<tr>
<td width="247">
<p>DECIPHER Population CNVs</p>
</td>
<td width="83">
<p>-</p>
</td>
<td width="273">
<p>http://decipher.sanger.ac.uk/</p>
</td>
</tr>
<tr>
<td width="247">
<p>DECIPHER CNV syndromes</p>
</td>
<td width="83">
<p>2020-01-19</p>
</td>
<td width="273">
<p>http://decipher.sanger.ac.uk/</p>
</td>
</tr>
<tr>
<td width="247">
<p>Mouse Genome Informatics</p>
</td>
<td width="83">
<p>2021-03-01</p>
</td>
<td width="273">
<p>http://www.informatics.jax.org/</p>
</td>
</tr>
<tr>
<td width="247">
<p>The Human Protein Atlas</p>
</td>
<td width="83">
<p>v.20.1</p>
</td>
<td width="273">
<p>http://www.proteinatlas.org/</p>
</td>
</tr>
<tr>
<td width="247">
<p>OHNOLOGS</p>
</td>
<td width="83">
<p>v.2.0</p>
</td>
<td width="273">
<p>http://ohnologs.curie.fr/</p>
</td>
</tr>
<tr>
<td width="247">
<p>STRING</p>
</td>
<td width="83">
<p>v.11</p>
</td>
<td width="273">
<p>https://string-db.org/</p>
</td>
</tr>
<tr>
<td width="247">
<p>OMIM</p>
</td>
<td width="83">
<p>2020-03-12</p>
</td>
<td width="273">
<p>http://www.omim.org/</p>
</td>
</tr>
<tr>
<td width="247">
<p>HUGO Gene Nomenclature Committee</p>
</td>
<td width="83">
<p>2021-03-03</p>
</td>
<td width="273">
<p>&nbsp;http://www.genenames.org/</p>
</td>
</tr>
<tr>
<td width="247">
<p>gnomAD Structural Variants (SVs)</p>
</td>
<td width="83">
<p>v.2.1</p>
</td>
<td width="273">
<p>&nbsp;https://gnomad.broadinstitute.org/</p>
</td>
</tr>
<tr>
<td width="247">
<p>Genomics England PanelApp</p>
</td>
<td width="83">
<p>-</p>
</td>
<td width="273">
<p>https://panelapp.genomicsengland.co.uk/</p>
</td>
</tr>
<tr>
<td width="247">
<p>ORPHANET</p>
</td>
<td width="83">
<p>2021-03-01</p>
</td>
<td width="273">
<p>https://www.orpha.net/consor/cgi-bin/index.php</p>
</td>
</tr>
<tr>
<td width="247">
<p>ClinGen &ndash; CNV syndromes</p>
</td>
<td width="83">
<p>v.1.1</p>
</td>
<td width="273">
<p>https://clinicalgenome.org/</p>
</td>
</tr>
<tr>
<td width="247">
<p>ClinGen &ndash; Dosage Sensitivity Map</p>
</td>
<td width="83">
<p>2021-03-03</p>
</td>
<td width="273">
<p>https://clinicalgenome.org/</p>
</td>
</tr>
<tr>
<td width="247">
<p>ClinVar</p>
</td>
<td width="83">
<p>2021-02-21</p>
</td>
<td width="273">
<p>https://www.ncbi.nlm.nih.gov/clinvar/</p>
</td>
</tr>
<tr>
<td width="247">
<p>GWAS catalog</p>
</td>
<td width="83">
<p>v.1.0</p>
</td>
<td width="273">
<p>https://www.ebi.ac.uk/gwas/</p>
</td>
</tr>
<tr>
<td width="247">
<p>denovo-db</p>
</td>
<td width="83">
<p>v.1.6.1</p>
</td>
<td width="273">
<p>http://denovo-db.gs.washington.edu/denovo-db/</p>
</td>
</tr>
<tr>
<td width="247">
<p>ENCODE Blacklist</p>
</td>
<td width="83">
<p>v.2</p>
</td>
<td width="273">
<p>https://github.com/Boyle-Lab/Blacklist/tree/master/lists</p>
</td>
</tr>
<tr>
<td width="247">
<p>The Human Phenotype Ontology (HPO)</p>
</td>
<td width="83">
<p>2021-02-09</p>
</td>
<td width="273">
<p>https://hpo.jax.org/app/</p>
</td>
</tr>
<tr>
<td width="247">
<p>miRTarBase</p>
</td>
<td width="83">
<p>8.0</p>
</td>
<td width="273">
<p>http://mirtarbase.cuhk.edu.cn/php/index.php</p>
</td>
</tr>
<tr>
<td width="247">
<p>TRRUST</p>
</td>
<td width="83">
<p>v.2</p>
</td>
<td width="273">
<p>https://www.grnpedia.org/trrust/</p>
</td>
</tr>
<tr>
<td width="247">
<p>lncrna2target</p>
</td>
<td width="83">
<p>v.2</p>
</td>
<td width="273">
<p>http://123.59.132.21/lncrna2target/</p>
</td>
</tr>
<tr>
<tr>
<td width="247">
<p>GeneHancer</p>
</td>
<td width="83">
<p>v.4.11</p>
</td>
<td width="273">
<p>-</p>
</td>
</tr>
<tr>
<td width="247">
<p>Mammalian Phenotype Ontology (MPO)</p>
</td>
<td width="83">
<p>2021-01-12</p>
</td>
<td width="273">
<p>http://www.informatics.jax.org/vocab/mp_ontology/</p>
</td>
</tr>
<tr>
<td width="247">
<p>The Genotype-Tissue Expression (GTEx)</p>
</td>
<td width="83">
<p>v.8</p>
</td>
<td width="273">
<p>https://www.gtexportal.org/home/</p>
</td>
</tr>
</tbody>
</table>

</center>

## R session



R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
  [1] bioloupe_0.0.0.9000         BioCircos_0.3.4             RColorBrewer_1.1-2          xgboost_0.90.0.2           
  [5] GenometriCorr_1.1.23        GenomicFeatures_1.38.2      vip_0.3.2                   networkD3_0.4              
  [9] tidytext_0.2.3              widyr_0.1.3                 igraph_1.2.4.1              ggraph_2.0.0               
 [13] shinyalert_1.0              formattable_0.2.0.1         ontologySimilarity_2.3      chromPlot_1.14.0           
 [17] UpSetR_1.4.0                shinymanager_1.0            shinyhelper_0.3.2           ggrepel_0.8.1              
 [21] reactable_0.1.0.1           rentrez_1.2.2               enrichplot_1.6.1            DOSE_3.12.0                
 [25] DescTools_0.99.31           plotly_4.9.0                shinycssloaders_0.2.0       ReactomePA_1.30.0          
 [29] gghighlight_0.2.0           highcharter_0.7.0           DT_0.9                      shinyjs_1.0                
 [33] shinyWidgets_0.4.9          echarts4r_0.2.3             shinyEffects_0.1.0          tablerDash_0.1.0           
 [37] shiny_1.4.0                 TissueEnrich_1.6.0          GSEABase_1.48.0             graph_1.64.0               
 [41] annotate_1.64.0             XML_3.98-1.20               SummarizedExperiment_1.16.0 DelayedArray_0.12.0        
 [45] BiocParallel_1.19.6         matrixStats_0.55.0          ensurer_1.1                 org.Hs.eg.db_3.10.0        
 [49] AnnotationDbi_1.48.0        Biobase_2.46.0              clusterProfiler_3.14.3      biovizBase_1.34.1          
 [53] ggbio_1.34.0                readxl_1.3.1                corrplot_0.84               broom_0.5.5                
 [57] ggridges_0.5.1              factoextra_1.0.7            plumber_0.4.6               bayesplot_1.7.1            
 [61] rstan_2.19.3                StanHeaders_2.19.2          overlapping_1.6             testthat_2.3.0             
 [65] ggpubr_0.2.3                magrittr_1.5                reticulate_1.13             applicable_0.0.1.1         
 [69] prettydoc_0.3.1             bayestestR_0.7.0            rstanarm_2.19.3             Rcpp_1.0.3                 
 [73] workflows_0.1.1             dials_0.0.6                 scales_1.0.0                rules_0.0.2                
 [77] xrf_0.2.0                   xrftest_0.2.0               rsample_0.0.6               patchwork_1.0.0.9000       
 [81] glue_1.4.2                  yardstick_0.0.6             parsnip_0.1.0               tune_0.1.0                 
 [85] furrr_0.2.1                 corrr_0.4.2                 ontologyIndex_2.5           tictoc_1.0                 
 [89] forcats_0.4.0               stringr_1.4.0               purrr_0.3.3                 readr_1.3.1                
 [93] tidyr_1.0.0                 tibble_2.1.3                ggplot2_3.3.0               tidyverse_1.2.1            
 [97] future_1.20.1               recipes_0.1.9               dplyr_1.0.2                 valr_0.5.0.9000            
[101] GenomicScores_1.10.0        biomaRt_2.42.0              rtracklayer_1.46.0          GenomicRanges_1.38.0       
[105] GenomeInfoDb_1.22.0         IRanges_2.20.0              S4Vectors_0.24.0            BiocGenerics_0.32.0        

loaded via a namespace (and not attached):
  [1] graphlayouts_0.5.0                      lattice_0.20-38                        
  [3] haven_2.1.1                             tcltk_3.6.0                            
  [5] expm_0.999-4                            vctrs_0.3.4                            
  [7] graphite_1.32.0                         usethis_1.5.1                          
  [9] mgcv_1.8-31                             blob_1.2.0                             
 [11] survival_3.1-8                          prodlim_2019.11.13                     
 [13] RBGL_1.62.1                             later_1.0.0                            
 [15] nloptr_1.2.1                            R.utils_2.9.0                          
 [17] DBI_1.0.0                               rappdirs_0.3.1                         
 [19] xopen_1.0.0                             zlibbioc_1.32.0                        
 [21] OrganismDbi_1.28.0                      htmlwidgets_1.5.1                      
 [23] mvtnorm_1.0-11                          inline_0.3.15                          
 [25] markdown_1.1                            tidygraph_1.1.2                        
 [27] Homo.sapiens_1.3.1                      promises_1.1.0                         
 [29] pkgload_1.0.2                           RcppParallel_5.0.3                     
 [31] Hmisc_4.2-0                             fs_1.3.1                               
 [33] fastmatch_1.1-0                         ranger_0.11.2                          
 [35] digest_0.6.22                           cowplot_1.0.0                          
 [37] glmnet_3.0-2                            janeaustenr_0.1.5                      
 [39] pkgconfig_2.0.3                         GO.db_3.10.0                           
 [41] dygraphs_1.1.1.6                        gower_0.2.1                            
 [43] iterators_1.0.12                        minqa_1.2.4                            
 [45] GPfit_1.0-8                             xfun_0.10                              
 [47] zoo_1.8-6                               tidyselect_1.1.0                       
 [49] reshape2_1.4.3                          rcmdcheck_1.3.3                        
 [51] sourcetools_0.1.7                       fuzzyjoin_0.1.5                        
 [53] viridisLite_0.3.0                       pkgbuild_1.0.6                         
 [55] rlang_0.4.8                             ensembldb_2.10.2                       
 [57] lhs_1.0.1                               modelr_0.1.5                           
 [59] lava_1.6.6                              europepmc_0.3                          
 [61] billboarder_0.2.7                       ggsignif_0.6.0                         
 [63] threejs_0.3.3                           labeling_0.3                           
 [65] GGally_2.1.0                            import_1.1.0                           
 [67] httpuv_1.5.2                            class_7.3-15                           
 [69] tokenizers_0.2.1                        reactome.db_1.70.0                     
 [71] shinystan_2.5.0                         DO.db_2.9                              
 [73] jsonlite_1.6                            XVector_0.26.0                         
 [75] bit_1.1-14                              mime_0.7                               
 [77] gridExtra_2.3                           Rsamtools_2.0.3                        
 [79] packrat_0.5.0                           stringi_1.4.3                          
 [81] insight_0.8.5                           processx_3.4.1                         
 [83] hardhat_0.1.2                           bitops_1.0-6                           
 [85] cli_2.0.2                               RSQLite_2.1.2                          
 [87] data.table_1.12.6                       rsconnect_0.8.15                       
 [89] rstudioapi_0.11                         GenomicAlignments_1.22.1               
 [91] nlme_3.1-143                            qvalue_2.18.0                          
 [93] VariantAnnotation_1.32.0                listenv_0.8.0                          
 [95] SnowballC_0.7.0                         miniUI_0.1.1.1                         
 [97] gridGraphics_0.4-1                      R.oo_1.22.0                            
 [99] dbplyr_1.4.2                            sessioninfo_1.1.1                      
[101] TTR_0.23-5                              lifecycle_0.2.0                        
[103] quantmod_0.4.17                         timeDate_3043.102                      
[105] commonmark_1.7                          munsell_0.5.0                          
[107] cellranger_1.1.0                        R.methodsS3_1.7.1                      
[109] proxyC_0.1.5                            codetools_0.2-16                       
[111] htmlTable_1.13.2                        triebeard_0.3.0                        
[113] rstantools_2.1.1                        xtable_1.8-4                           
[115] BiocManager_1.30.9                      farver_1.1.0                           
[117] parallelly_1.21.0                       AnnotationHub_2.18.0                   
[119] askpass_1.1                             shinythemes_1.1.2                      
[121] gwascat_2.18.0                          dichromat_2.0-0                        
[123] cluster_2.1.0                           Matrix_1.2-18                          
[125] ellipsis_0.3.0                          prettyunits_1.0.2                      
[127] lubridate_1.7.4                         fgsea_1.12.0                           
[129] remotes_2.1.0                           liftOver_1.10.0                        
[131] arulesCBA_1.1.6                         htmltools_0.4.0                        
[133] BiocFileCache_1.10.0                    yaml_2.2.0                             
[135] loo_2.4.1                               utf8_1.1.4                             
[137] interactiveDisplayBase_1.24.0           foreign_0.8-75                         
[139] withr_2.1.2                             bit64_0.9-7                            
[141] foreach_1.4.7                           ProtGenerics_1.18.0                    
[143] Biostrings_2.52.0                       GOSemSim_2.12.1                        
[145] devtools_2.2.1                          memoise_1.1.0                          
[147] evaluate_0.14                           callr_3.3.2                            
[149] ps_1.3.0                                curl_4.2                               
[151] fansi_0.4.0                             TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2
[153] urltools_1.7.3                          xts_0.11-2                             
[155] acepack_1.4.1                           checkmate_1.9.4                        
[157] desc_1.2.0                              Gviz_1.30.3                            
[159] rlist_0.4.6.1                           rprojroot_1.3-2                        
[161] tools_3.6.0                             arules_1.6-4                           
[163] RCurl_1.95-4.12                         ggplotify_0.0.5                        
[165] xml2_1.2.2                              httr_1.4.1                             
[167] assertthat_0.2.1                        rmarkdown_2.1                          
[169] boot_1.3-24                             globals_0.13.1                         
[171] R6_2.5.0                                AnnotationFilter_1.10.0                
[173] nnet_7.3-12                             progress_1.2.2                         
[175] gtools_3.8.1                            shape_1.4.4                            
[177] BiocVersion_3.10.1                      splines_3.6.0                          
[179] colorspace_1.4-1                        generics_0.0.2                         
[181] discretization_1.0-1                    base64enc_0.1-3                        
[183] pillar_1.4.2                            tweenr_1.0.1                           
[185] rvcheck_0.1.8                           GenomeInfoDbData_1.2.2                 
[187] plyr_1.8.4                              gtable_0.3.0                           
[189] rvest_0.3.4                             plyranges_1.6.10                       
[191] colourpicker_1.0                        knitr_1.25                             
[193] latticeExtra_0.6-28                     fastmap_1.0.1                          
[195] Cairo_1.5-10                            crosstalk_1.0.0                        
[197] openssl_1.4.1                           BSgenome_1.54.0                        
[199] backports_1.1.5                         ipred_0.9-9                            
[201] lme4_1.1-21                             hms_0.5.2                              
[203] ggforce_0.3.1                           polyclip_1.10-0                        
[205] DiceDesign_1.8-1                        lazyeval_0.2.2                         
[207] Formula_1.2-3                           whisker_0.4                            
[209] crayon_1.3.4                            MASS_7.3-51.5                          
[211] pROC_1.16.1                             roxygen2_6.1.1                         
[213] viridis_0.5.1                           reshape_0.8.8                          
[215] rpart_4.1-15                            compiler_3.6.0     
